server:
  port: 8022
spring:
  application:
    # 指定注册到nacos server上的服务名称
    name: microservice-consumer-movie
  cloud:
    nacos:
      discovery:
        server-addr: 120.76.130.43:8848
feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'